In [2]:
import jax
import jax.numpy as jnp

In [3]:
a = jnp.array([-1, -2, -3, 1, 2, 3])
a.at[:3].apply(jax.nn.relu)

Array([0, 0, 0, 1, 2, 3], dtype=int32)

In [6]:
a[:3]

Array([-1, -2, -3], dtype=int32)

In [6]:
def func1(x, mu):

    return x[0] * mu + x[1]
x = jnp.array([jnp.pi / 4, jnp.pi / 2])
func1(x, 0.1)

Array(1.6493362, dtype=float32)

In [7]:
grad = jax.grad(func1, argnums=0)
grad(x, 0.1)

Array([0.1, 1. ], dtype=float32)

In [8]:
grad(x, 0.2)

Array([0.2, 1. ], dtype=float32)

In [16]:
jax.jacrev(func1, argnums = 1)(jnp.array([1.0, 2.0]), 1.0)

Array([0., 0., 1.], dtype=float32, weak_type=True)

In [22]:
def func1(x):

    return jnp.asarray([0.5 -  2* x.T@x])

def func2(x):

    return jnp.asarray([0.5 - x.T@x, 0.5 - x.T@x])

x = jnp.array([1.0, 2.0])

print(jax.jacrev(func1)(x))
print(jax.jacrev(func2)(x))

[[-4. -8.]]
[[-2. -4.]
 [-2. -4.]]


In [31]:
jnp.vstack([jax.jacrev(func1, argnums=0)(x), jax.jacrev(func2, argnums=0)(x)]).T

Array([[-4., -2., -2.],
       [-8., -4., -4.]], dtype=float32)

In [26]:
jnp.hstack([func1(x), func2(x)])

Array([-9.5, -4.5, -4.5], dtype=float32)

In [46]:
a = [1, 2, 3]
b = [1]

foo = jnp.asarray([*a, *b])
(foo > 0).all()

Array(True, dtype=bool)

In [45]:
bar = foo
bar = bar.at[0].set(-5)
(bar[:2] > 0).all()

Array(False, dtype=bool)

In [38]:
bar

Array([-5,  2,  3,  1], dtype=int32)